In [1]:
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
import matplotlib.pyplot as plt
plt.imshow(x_train[59999])

In [5]:
x_train=x_train.reshape(60000,28,28,1)
x_test=x_test.reshape(10000,28,28,1)

In [6]:
y_train[2]

4

In [7]:
from keras.utils import to_categorical
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)

In [8]:
y_train[59999]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)

In [9]:
from keras.models import Sequential
from keras.layers import Dense,Flatten,Conv2D,MaxPooling2D

In [11]:
model=Sequential()
model.add(Conv2D(32,kernel_size=3,activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2) ))
model.add(Conv2D(64,kernel_size=3,activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2) ))
model.add(Flatten())
model.add(Dense(units=32,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [12]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=5)

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 207s 3ms/step - loss: 1.1899 - acc: 0.8089 - val_loss: 0.0933 - val_acc: 0.9734
Epoch 2/5
60000/60000 [==============================] - 204s 3ms/step - loss: 0.0701 - acc: 0.9793 - val_loss: 0.0622 - val_acc: 0.9817
Epoch 3/5
60000/60000 [==============================] - 208s 3ms/step - loss: 0.0511 - acc: 0.9844 - val_loss: 0.0563 - val_acc: 0.9814
Epoch 4/5
60000/60000 [==============================] - 201s 3ms/step - loss: 0.0412 - acc: 0.9874 - val_loss: 0.0457 - val_acc: 0.9869
Epoch 5/5
60000/60000 [==============================] - 207s 3ms/step - loss: 0.0346 - acc: 0.9889 - val_loss: 0.0515 - val_acc: 0.9846


In [16]:
model.predict(x_test[:4])

array([[3.8019035e-13, 7.6502865e-10, 3.0306799e-07, 2.7533245e-09,
        2.6803619e-07, 2.3122242e-10, 6.2909666e-16, 9.9999630e-01,
        2.6802542e-09, 3.1018094e-06],
       [4.1177102e-09, 6.1755667e-10, 9.9999952e-01, 2.8421410e-14,
        8.6655814e-14, 2.8012548e-14, 4.3712200e-07, 2.0637873e-10,
        3.6496360e-08, 7.5382604e-13],
       [6.4375488e-10, 9.9998748e-01, 3.9593629e-06, 7.1585571e-11,
        1.6252508e-06, 1.0526273e-08, 8.5894463e-08, 9.1595592e-07,
        4.7447238e-06, 1.0708375e-06],
       [9.9998724e-01, 2.0787484e-12, 3.2318814e-10, 1.0455394e-12,
        2.3565812e-09, 2.6105347e-08, 1.7458322e-06, 7.1535808e-09,
        1.6682727e-06, 9.3529825e-06]], dtype=float32)

In [18]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)